### ISSUE TITLE
Batch creating student account

### ISSUE THREAD

**Issue by larryyueli** [quizzard-edu/quizzard#117] opened 2017-10-25 03:48 UTC
In the case that we don't use UTORID for Quizzard. We want to be able to create batch-create user account while assigning each of them an initial password. 

The UI for this would be that the instructor uploads a file where each line has a username and a password.

**Comment by esteeroramy** [comment] 2017-10-25 13:02
Duplicate of #53 ?

**Comment by ahmedqarmout2** [comment] 2017-10-25 13:25
I think so, I will work on this tasks

**Closed as completed** 2017-11-07 04:27 UTC
Labels: Feature
